/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlydiemsinhviet;

import javax.swing.JFrame;

/**
 *
 * @author DELL
 */
public class JFrameGVu extends javax.swing.JFrame {

    /**
     * Creates new form JFrameGVu
     */
    public JFrameGVu() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setTitle("Giáo Vụ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemDSlop = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemThemSV = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(400, 800));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.PAGE_START);

        jMenuBar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar2.setPreferredSize(new java.awt.Dimension(166, 30));

        jMenu3.setText("Nhập");

        jMenuItemDSlop.setText("Danh Sách Lớp");
        jMenuItemDSlop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDSlopActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemDSlop);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Thêm");

        jMenuItemThemSV.setText("Sinh Viên");
        jMenuItemThemSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemThemSVActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemThemSV);

        jMenuBar2.add(jMenu4);

        jMenu5.setText("Xem");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Sửa");
        jMenuBar2.add(jMenu6);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemDSlopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDSlopActionPerformed
        // TODO add your handling code here:
        JInternalFrameImportdsLop DSLOP = new JInternalFrameImportdsLop();
        DSLOP.setVisible(true);
        this.jDesktopPane1.add(DSLOP);
    }//GEN-LAST:event_jMenuItemDSlopActionPerformed

    private void jMenuItemThemSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemThemSVActionPerformed
        // TODO add your handling code here:
        JInternalFrameThemSinhVien TSV = new JInternalFrameThemSinhVien();
        TSV.setVisible(true);
        this.jDesktopPane1.add(TSV);
    }//GEN-LAST:event_jMenuItemThemSVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameGVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameGVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameGVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameGVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameGVu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItemDSlop;
    private javax.swing.JMenuItem jMenuItemThemSV;
    // End of variables declaration//GEN-END:variables
}
