/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlydiemsinhviet;

import dao.DiemDAO;
import pojos.Diem;
import pojos.DiemId;
import java.util.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import util.myCSVFile;

/**
 *
 * @author DELL
 */
public class JInternalFrameBangDiem extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrameBangDiem
     */
    public JInternalFrameBangDiem() {
        initComponents();
        setLocation(200, 30);
        loadDsLopMon();
    }

    private List<Diem> dsDiemSV;
    private List<String> dsLop;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBangDiem = new javax.swing.JTable();
        jComboBoxLopMon = new javax.swing.JComboBox<>();
        jLabelLop = new javax.swing.JLabel();
        jButtonOpenFile = new javax.swing.JButton();
        jButtonImport = new javax.swing.JButton();

        setClosable(true);

        jTableBangDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null ,null},
                {null, null, null, null, null, null ,null}
            },
            new String [] {
                "STT", "MSSV", "Họ tên", "Điểm GK","Điểm CK","Điểm khác","Điểm tổng"
            }
        ));
        jScrollPane1.setViewportView(jTableBangDiem);

        jComboBoxLopMon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {""}));

        jLabelLop.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelLop.setText("Lớp ");

        jButtonOpenFile.setText("Open File");
        jButtonOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenFileActionPerformed(evt);
            }
        });

        jButtonImport.setText("Import");
        jButtonImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonImport)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelLop, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonOpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxLopMon, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonOpenFile)
                    .addComponent(jComboBoxLopMon, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jLabelLop, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButtonImport)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenFileActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "CSV UTF-8(Comma delimited)(*.csv)", "csv");
        chooser.setFileFilter(filter);

        int returnVal = chooser.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            System.out.println(chooser.getSelectedFile());
            dsDiemSV = null;
            String fileChooser = chooser.getSelectedFile().toString();

            DefaultTableModel defaultModel = new DefaultTableModel();
            //Load data to table LOP-MONHOC
            defaultModel.addColumn("STT");
            defaultModel.addColumn("MSSV");
            defaultModel.addColumn("Họ Tên");
            defaultModel.addColumn("Điểm GK");
            defaultModel.addColumn("Điểm CK");
            defaultModel.addColumn("Điểm Khác");
            defaultModel.addColumn("Điểm Tổng");

            dsDiemSV = util.myCSVFile.importBangDiem(fileChooser, defaultModel);
            if (dsDiemSV != null) {
                this.jLabelLop.setText(dsDiemSV.get(0).getId().getMalop());
            }
            this.jTableBangDiem.setModel(defaultModel);
            this.jTableBangDiem.repaint();
            this.jTableBangDiem.revalidate();
            this.jTableBangDiem.setVisible(true);
        }
    }//GEN-LAST:event_jButtonOpenFileActionPerformed

    private void jButtonImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportActionPerformed
        // TODO add your handling code here:
        String lop = jComboBoxLopMon.getSelectedItem().toString();
        if (lop == "") {
            if (dsDiemSV != null) {
                DiemDAO.themDiemNSV(dsDiemSV);
                JOptionPane.showMessageDialog(null, "Thêm điểm thành công");
                dsLop.add(jLabelLop.getText());
            } else {
                JOptionPane.showMessageDialog(null, "Danh sách đã tồn tại");
            }
        }
    }//GEN-LAST:event_jButtonImportActionPerformed

    private void loadDsLopMon() {
        dsLop = DiemDAO.dsLop();
        if (dsLop != null) {
            dsLop.add(0, "");
            jComboBoxLopMon.setModel(new javax.swing.DefaultComboBoxModel<>(dsLop.toArray(new String[0])));
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonImport;
    private javax.swing.JButton jButtonOpenFile;
    private javax.swing.JComboBox<String> jComboBoxLopMon;
    private javax.swing.JLabel jLabelLop;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBangDiem;
    // End of variables declaration//GEN-END:variables
}
