/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlydiemsinhviet;

import dao.DiemDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import pojos.Phuckhao;
import dao.PhucKhaoDAO;
import dao.SinhVienDAO;
import javax.swing.JOptionPane;
import pojos.Diem;
import pojos.DiemId;

/**
 *
 * @author DELL
 */
public class JInternalFramePhucKhao extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFramePhucKhao
     */
    private List<Phuckhao> ds;
    private Phuckhao pkSelect;

    public JInternalFramePhucKhao() {
        initComponents();
        setLocation(150, 25);
        loadDSPhucKhao();
        pkSelect = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDSPhucKhao = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldMSSV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldHoTen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDiemMongMuon = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldLyDo = new javax.swing.JTextField();
        jButtonCapNhat = new javax.swing.JButton();
        jButtonKoCapNhat = new javax.swing.JButton();
        jTextFieldCotDiem = new javax.swing.JTextField();

        setClosable(true);

        jTableDSPhucKhao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "MSSV","Môn Phúc khảo","Tình Trạng Phúc Khảo"
            }
        ));
        jTableDSPhucKhao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDSPhucKhaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDSPhucKhao);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true), "Phúc Khảo"));

        jLabel1.setText("MSSV : ");

        jTextFieldMSSV.setEditable(false);

        jLabel2.setText("Họ Tên: ");

        jTextFieldHoTen.setEditable(false);

        jLabel3.setText("Môn: ");

        jTextFieldMon.setEditable(false);

        jLabel4.setText("Cột điểm :");

        jLabel5.setText("Điểm mong muốn :");

        jTextFieldDiemMongMuon.setEditable(false);

        jLabel6.setText("Lý do: ");

        jTextFieldLyDo.setEditable(false);

        jButtonCapNhat.setText("Cập Nhật ");
        jButtonCapNhat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jButtonCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCapNhatActionPerformed(evt);
            }
        });

        jButtonKoCapNhat.setText("Không Cập Nhật");
        jButtonKoCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKoCapNhatActionPerformed(evt);
            }
        });

        jTextFieldCotDiem.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jTextFieldCotDiem)))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldDiemMongMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTextFieldMon, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jTextFieldLyDo, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addComponent(jButtonCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonKoCapNhat))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldMon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldCotDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jTextFieldDiemMongMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldLyDo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonKoCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCapNhatActionPerformed
        // TODO add your handling code here:
        CapNhatTrangThai(2);
    }//GEN-LAST:event_jButtonCapNhatActionPerformed

    private void jTableDSPhucKhaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDSPhucKhaoMouseClicked
        // TODO add your handling code here:
        int row = jTableDSPhucKhao.getSelectedRow();
        if (row < 0) {
            return;
        }
        pkSelect = (Phuckhao) ds.get(row);
        String mssv = pkSelect.getId().getMssv();
        String hoten = SinhVienDAO.getHoTenSV(mssv);

        jTextFieldMSSV.setText(mssv);
        jTextFieldHoTen.setText(hoten);
        jTextFieldMon.setText(pkSelect.getId().getMamon());
        jTextFieldCotDiem.setText(pkSelect.getCotdiem());
        jTextFieldDiemMongMuon.setText(pkSelect.getDiemmongmuon().toString());
        jTextFieldLyDo.setText(pkSelect.getLydo());
    }//GEN-LAST:event_jTableDSPhucKhaoMouseClicked

    private void jButtonKoCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKoCapNhatActionPerformed
        // TODO add your handling code here:

        CapNhatTrangThai(1);
    }//GEN-LAST:event_jButtonKoCapNhatActionPerformed

    private void loadDSPhucKhao() {
        DefaultTableModel model = (DefaultTableModel) jTableDSPhucKhao.getModel();
        model.setRowCount(0);
        ds = PhucKhaoDAO.layDSPhucKhao();
        if (ds == null) {
            return;
        }

        for (Phuckhao pk : ds) {
            String tinhtrang = null;
            int tt = pk.getTinhtrang();
            tinhtrang = gettinhtrang(tt);
            model.addRow(new Object[]{pk.getId().getMssv(), pk.getId().getMamon(), tinhtrang});
        }
    }

    private void CapNhatTrangThai(int tt) {
        if (pkSelect == null) {
            return;
        }
        if (pkSelect.getTinhtrang() != 0) {
            JOptionPane.showMessageDialog(null, "Trạng thái đã được cập nhật");
            return;
        }
        //Sửa điểm

        boolean result = PhucKhaoDAO.capNhatTinhTrang(pkSelect.getId(), tt);
        if (result == true) {
            JOptionPane.showMessageDialog(null, "Cập nhật trạng thái thành công");

            //sửa trên table
            int row = jTableDSPhucKhao.getSelectedRow();
            jTableDSPhucKhao.setValueAt(gettinhtrang(tt), row, 2);

            //sửa vào data
            if (tt == 2) {//cập nhật lại điểm
                //System.out.println(pkSelect.getCotdiem());
                DiemId id = new DiemId(pkSelect.getId().getMssv(), pkSelect.getId().getMamon());
                Diem diemSV = DiemDAO.layThongTinDiemSV(id);
                if (diemSV == null) {
                    return;
                }
                if (pkSelect.getCotdiem().compareTo("Điểm GK") == 0) {
                    System.out.println("Điểm Gk");
                    diemSV.setDiemGk(pkSelect.getDiemmongmuon());
                } else if (pkSelect.getCotdiem().compareTo("Điểm CK") == 0) {
                    System.out.println("Điểm ck");
                    diemSV.setDiemCk(pkSelect.getDiemmongmuon());
                } else if (pkSelect.getCotdiem().compareTo("Điểm Khác") == 0) {
                    System.out.println("Điểm KHÁC");
                    diemSV.setDiemKhac(pkSelect.getDiemmongmuon());
                } else if (pkSelect.getCotdiem().compareTo("Điểm Tổng") == 0) {
                    System.out.println("Điểm TỔNG");
                    diemSV.setDiemTong(pkSelect.getDiemmongmuon());
                }
                float DiemTong = DiemDAO.tinhDiemTong(diemSV);
                diemSV.setDiemTong(DiemTong);
                if (DiemTong >= 5) {
                    diemSV.setDau("Đạt");
                } else {
                    diemSV.setDau(null);
                }
                DiemDAO.capNhatDiemSV(diemSV);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Cập nhật trạng thái không thành công");
        }
    }

    private String gettinhtrang(int tt) {
        if (tt == 0) {
            return "chưa xem";
        } else if (tt == 1) {
            return "không cập nhật điểm";
        } else if (tt == 2) {
            return "đã cập nhật điểm";
        }
        return null;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCapNhat;
    private javax.swing.JButton jButtonKoCapNhat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDSPhucKhao;
    private javax.swing.JTextField jTextFieldCotDiem;
    private javax.swing.JTextField jTextFieldDiemMongMuon;
    private javax.swing.JTextField jTextFieldHoTen;
    private javax.swing.JTextField jTextFieldLyDo;
    private javax.swing.JTextField jTextFieldMSSV;
    private javax.swing.JTextField jTextFieldMon;
    // End of variables declaration//GEN-END:variables
}
