/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlydiemsinhviet;

import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import pojos.LopMonhoc;
import util.myCSVFile;

/**
 *
 * @author DELL
 */
public class JInternalFrameImportLopMonHoc extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrameImportLopMonHoc
     */
    public JInternalFrameImportLopMonHoc() {
        initComponents();
        setLocation(200, 30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLopMonHoc = new javax.swing.JTable();
        jButtonOpenFIle = new javax.swing.JButton();
        jLabelLop = new javax.swing.JLabel();

        jTableLopMonHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "MSSV", "Họ Tên", "Giới Tính","CMND"
            }
        ));
        jScrollPane1.setViewportView(jTableLopMonHoc);

        jButtonOpenFIle.setText("Open File");
        jButtonOpenFIle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenFIleActionPerformed(evt);
            }
        });

        jLabelLop.setText("Lớp");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonOpenFIle)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLop, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButtonOpenFIle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jLabelLop)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOpenFIleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenFIleActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "CSV UTF-8(Comma delimited)(*.csv)", "csv");
        chooser.setFileFilter(filter);

        int returnVal = chooser.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            System.out.println(chooser.getSelectedFile());
            String fileChooser = chooser.getSelectedFile().toString();
            List<LopMonhoc> dsLOPmonHoc = null;
            DefaultTableModel LMH = new DefaultTableModel();

            //loadDataTable(tkb);
            LMH.addColumn("STT");
            LMH.addColumn("MSSV");
            LMH.addColumn("Họ Tên");
            LMH.addColumn("Giới Tính");
            LMH.addColumn("CMND");
            dsLOPmonHoc = myCSVFile.importLopMonHoc(fileChooser, LMH);
            this.jLabelLop.setText(dsLOPmonHoc.get(0).getMalop());
            this.jTableLopMonHoc.setModel(LMH);
            this.jLabelLop.repaint();
            this.jLabelLop.revalidate();
            this.jLabelLop.setVisible(true);
        }
    }//GEN-LAST:event_jButtonOpenFIleActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOpenFIle;
    private javax.swing.JLabel jLabelLop;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLopMonHoc;
    // End of variables declaration//GEN-END:variables
}
