/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlydiemsinhviet;

import dao.DiemDAO;
import dao.LopMonHocDAO;
import dao.SinhVienDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import pojos.Diem;
import dao.PhucKhaoDAO;
import javax.swing.JOptionPane;
import pojos.Phuckhao;
import pojos.PhuckhaoId;

/**
 *
 * @author DELL
 */
public class JInternalFrameSVXemDiem extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrameSVXemDiem
     */
    private String username;
    private String hoten;

    public JInternalFrameSVXemDiem() {
        initComponents();
        setLocation(150, 25);
        //username = JFrameMain.username;
        username = "1742005";
        hoten = SinhVienDAO.getHoTenSV(username);
        loadDataTable();
        loadPhucKhao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDSDiem = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldMSSV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldHoTen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxCotDiem = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDiemMongMuon = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldLyDo = new javax.swing.JTextField();
        jButtonNopDon = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Xem Điểm / Phúc Khảo"));
        setClosable(true);

        jTableDSDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null,null, null, null},
                {null, null, null, null,null, null, null},
            },
            new String [] {
                "Mã môn","Tên Môn", "Điểm GK", "Điểm CK", "Điểm Khác","Điểm Tổng","Đậu/Rớt"
            }
        ));
        jTableDSDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDSDiemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDSDiem);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true), "Phúc Khảo"));

        jLabel1.setText("MSSV : ");

        jTextFieldMSSV.setEditable(false);

        jLabel2.setText("Họ Tên: ");

        jTextFieldHoTen.setEditable(false);

        jLabel3.setText("Môn: ");

        jTextFieldMon.setEditable(false);

        jLabel4.setText("Cột điểm :");

        jComboBoxCotDiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Điểm GK", "Điểm CK", "Điểm Khác", "Điểm Tổng" }));

        jLabel5.setText("Điểm mong muốn :");

        jLabel6.setText("Lý do: ");

        jButtonNopDon.setText("Nộp Đơn");
        jButtonNopDon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jButtonNopDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNopDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxCotDiem, 0, 146, Short.MAX_VALUE)
                                    .addComponent(jTextFieldMSSV))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldHoTen)
                                    .addComponent(jTextFieldDiemMongMuon, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)))
                            .addComponent(jTextFieldMon, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jTextFieldLyDo, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                .addComponent(jButtonNopDon, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldMon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxCotDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDiemMongMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldLyDo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonNopDon, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1057, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableDSDiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDSDiemMouseClicked
        // TODO add your handling code here:
        int row = jTableDSDiem.getSelectedRow();
        if (row >= 0) {
            String mamon = jTableDSDiem.getValueAt(row, 0).toString();
            jTextFieldMon.setText(mamon);
        }

    }//GEN-LAST:event_jTableDSDiemMouseClicked

    private void jButtonNopDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNopDonActionPerformed
        // TODO add your handling code here:

        int result = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn phúc khảo không ?");
        if (result == 0) {
            PhuckhaoId id = new PhuckhaoId(username, jTextFieldMon.getText());
            String cotdiem = jComboBoxCotDiem.getSelectedItem().toString();
            Float diemMoi = Float.parseFloat(jTextFieldDiemMongMuon.getText());
            Phuckhao pk = new Phuckhao(id, hoten, cotdiem, diemMoi, jTextFieldLyDo.getText(), 0);
            boolean kq = PhucKhaoDAO.themDonPhucKhao(pk);
            if (kq == true) {
                JOptionPane.showMessageDialog(null, "Đơn của bạn đã được gửi đến giáo vụ");
            } else {
                JOptionPane.showMessageDialog(null, "Đơn của bạn đã được nộp trước đó");
            }

        }
    }//GEN-LAST:event_jButtonNopDonActionPerformed

    private void loadDataTable() {
        DefaultTableModel model = (DefaultTableModel) jTableDSDiem.getModel();
        model.setRowCount(0);
        List<Diem> dsDiemSV = DiemDAO.layDiemMotSV(username);

        if (dsDiemSV == null) {
            return;
        }

        for (Diem d : dsDiemSV) {
            String mon = LopMonHocDAO.tenMonofLop(d.getId().getMalop());
            model.addRow(new Object[]{d.getId().getMalop(), mon,
                d.getDiemGk(), d.getDiemCk(), d.getDiemKhac(), d.getDiemTong(), d.getDau()});
        }

    }

    private void loadPhucKhao() {
        //load Thong tin sinh vien
        jTextFieldMSSV.setText(username);
        jTextFieldHoTen.setText(hoten);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNopDon;
    private javax.swing.JComboBox<String> jComboBoxCotDiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDSDiem;
    private javax.swing.JTextField jTextFieldDiemMongMuon;
    private javax.swing.JTextField jTextFieldHoTen;
    private javax.swing.JTextField jTextFieldLyDo;
    private javax.swing.JTextField jTextFieldMSSV;
    private javax.swing.JTextField jTextFieldMon;
    // End of variables declaration//GEN-END:variables
}
