package pojos;
// Generated 20-Jun-2020 22:28:32 by Hibernate Tools 4.3.1



/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private String username;
     private String password;
     private Integer loaiTk;

    public Account() {
    }

	
    public Account(String username, String password) {
        this.username = username;
        this.password = password;
    }
    public Account(String username, String password, Integer loaiTk) {
       this.username = username;
       this.password = password;
       this.loaiTk = loaiTk;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getLoaiTk() {
        return this.loaiTk;
    }
    
    public void setLoaiTk(Integer loaiTk) {
        this.loaiTk = loaiTk;
    }




}


