package pojos;
// Generated 04-Jun-2020 11:08:46 by Hibernate Tools 4.3.1

/**
 * DiemId generated by hbm2java
 */
public class DiemId implements java.io.Serializable {

    private String mssv;
    private String malop;

    public DiemId() {
    }

    public DiemId(String mssv, String malop) {
        this.mssv = mssv;
        this.malop = malop;
    }

    public String getMssv() {
        return this.mssv;
    }

    public void setMssv(String mssv) {
        this.mssv = mssv;
    }

    public String getMalop() {
        return this.malop;
    }

    public void setMalop(String malop) {
        this.malop = malop;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof DiemId)) {
            return false;
        }
        DiemId castOther = (DiemId) other;

        return ((this.getMssv() == castOther.getMssv()) || (this.getMssv() != null && castOther.getMssv() != null && this.getMssv().equals(castOther.getMssv())))
                && ((this.getMalop() == castOther.getMalop()) || (this.getMalop() != null && castOther.getMalop() != null && this.getMalop().equals(castOther.getMalop())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getMssv() == null ? 0 : this.getMssv().hashCode());
        result = 37 * result + (getMalop() == null ? 0 : this.getMalop().hashCode());
        return result;
    }

}
