package pojos;
// Generated 11-Jun-2020 11:09:51 by Hibernate Tools 4.3.1



/**
 * Giaovu generated by hbm2java
 */
public class Giaovu  implements java.io.Serializable {


     private String magiaovu;
     private String password;

    public Giaovu() {
    }

    public Giaovu(String magiaovu, String password) {
       this.magiaovu = magiaovu;
       this.password = password;
    }
   
    public String getMagiaovu() {
        return this.magiaovu;
    }
    
    public void setMagiaovu(String magiaovu) {
        this.magiaovu = magiaovu;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


