package pojos;
// Generated 11-Jun-2020 11:09:51 by Hibernate Tools 4.3.1



/**
 * LopMonhoc generated by hbm2java
 */
public class LopMonhoc  implements java.io.Serializable {


     private LopMonhocId id;
     private String mamon;

    public LopMonhoc() {
    }

    public LopMonhoc(LopMonhocId id, String mamon) {
       this.id = id;
       this.mamon = mamon;
    }
   
    public LopMonhocId getId() {
        return this.id;
    }
    
    public void setId(LopMonhocId id) {
        this.id = id;
    }
    public String getMamon() {
        return this.mamon;
    }
    
    public void setMamon(String mamon) {
        this.mamon = mamon;
    }




}


