package pojos;
// Generated 11-Jun-2020 11:09:51 by Hibernate Tools 4.3.1



/**
 * LopMonhocId generated by hbm2java
 */
public class LopMonhocId  implements java.io.Serializable {


     private String malop;
     private String mssv;

    public LopMonhocId() {
    }

    public LopMonhocId(String malop, String mssv) {
       this.malop = malop;
       this.mssv = mssv;
    }
   
    public String getMalop() {
        return this.malop;
    }
    
    public void setMalop(String malop) {
        this.malop = malop;
    }
    public String getMssv() {
        return this.mssv;
    }
    
    public void setMssv(String mssv) {
        this.mssv = mssv;
    }




}


