package pojos;
// Generated 20-Jun-2020 22:28:32 by Hibernate Tools 4.3.1



/**
 * LopMonhoc generated by hbm2java
 */
public class LopMonhoc  implements java.io.Serializable {


     private LopMonhocId id;

    public LopMonhoc() {
    }

    public LopMonhoc(LopMonhocId id) {
       this.id = id;
    }
   
    public LopMonhocId getId() {
        return this.id;
    }
    
    public void setId(LopMonhocId id) {
        this.id = id;
    }




}


