package pojos;
// Generated 13-Jun-2020 10:53:55 by Hibernate Tools 4.3.1



/**
 * LopMonhocId generated by hbm2java
 */
public class LopMonhocId  implements java.io.Serializable {


     private String malop;
     private String mssv;

    public LopMonhocId() {
    }

    public LopMonhocId(String malop, String mssv) {
       this.malop = malop;
       this.mssv = mssv;
    }
   
    public String getMalop() {
        return this.malop;
    }
    
    public void setMalop(String malop) {
        this.malop = malop;
    }
    public String getMssv() {
        return this.mssv;
    }
    
    public void setMssv(String mssv) {
        this.mssv = mssv;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LopMonhocId) ) return false;
		 LopMonhocId castOther = ( LopMonhocId ) other; 
         
		 return ( (this.getMalop()==castOther.getMalop()) || ( this.getMalop()!=null && castOther.getMalop()!=null && this.getMalop().equals(castOther.getMalop()) ) )
 && ( (this.getMssv()==castOther.getMssv()) || ( this.getMssv()!=null && castOther.getMssv()!=null && this.getMssv().equals(castOther.getMssv()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMalop() == null ? 0 : this.getMalop().hashCode() );
         result = 37 * result + ( getMssv() == null ? 0 : this.getMssv().hashCode() );
         return result;
   }   


}


