package pojos;
// Generated 12-Jun-2020 18:52:38 by Hibernate Tools 4.3.1



/**
 * LopMonhoc generated by hbm2java
 */
public class LopMonhoc  implements java.io.Serializable {


     private String malop;
     private String mssv;

    public LopMonhoc() {
    }

    public LopMonhoc(String malop, String mssv) {
       this.malop = malop;
       this.mssv = mssv;
    }
   
    public String getMalop() {
        return this.malop;
    }
    
    public void setMalop(String malop) {
        this.malop = malop;
    }
    public String getMssv() {
        return this.mssv;
    }
    
    public void setMssv(String mssv) {
        this.mssv = mssv;
    }




}


