package pojos;
// Generated 04-Jun-2020 11:08:46 by Hibernate Tools 4.3.1



/**
 * PhuckhaoId generated by hbm2java
 */
public class PhuckhaoId  implements java.io.Serializable {


     private String mssv;
     private String mamon;

    public PhuckhaoId() {
    }

    public PhuckhaoId(String mssv, String mamon) {
       this.mssv = mssv;
       this.mamon = mamon;
    }
   
    public String getMssv() {
        return this.mssv;
    }
    
    public void setMssv(String mssv) {
        this.mssv = mssv;
    }
    public String getMamon() {
        return this.mamon;
    }
    
    public void setMamon(String mamon) {
        this.mamon = mamon;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PhuckhaoId) ) return false;
		 PhuckhaoId castOther = ( PhuckhaoId ) other; 
         
		 return ( (this.getMssv()==castOther.getMssv()) || ( this.getMssv()!=null && castOther.getMssv()!=null && this.getMssv().equals(castOther.getMssv()) ) )
 && ( (this.getMamon()==castOther.getMamon()) || ( this.getMamon()!=null && castOther.getMamon()!=null && this.getMamon().equals(castOther.getMamon()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMssv() == null ? 0 : this.getMssv().hashCode() );
         result = 37 * result + ( getMamon() == null ? 0 : this.getMamon().hashCode() );
         return result;
   }   


}


