package pojos;
// Generated 11-Jun-2020 11:09:51 by Hibernate Tools 4.3.1



/**
 * ThoikhoabieuId generated by hbm2java
 */
public class ThoikhoabieuId  implements java.io.Serializable {


     private String mamon;
     private String lop;

    public ThoikhoabieuId() {
    }

    public ThoikhoabieuId(String mamon, String lop) {
       this.mamon = mamon;
       this.lop = lop;
    }
   
    public String getMamon() {
        return this.mamon;
    }
    
    public void setMamon(String mamon) {
        this.mamon = mamon;
    }
    public String getLop() {
        return this.lop;
    }
    
    public void setLop(String lop) {
        this.lop = lop;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ThoikhoabieuId) ) return false;
		 ThoikhoabieuId castOther = ( ThoikhoabieuId ) other; 
         
		 return ( (this.getMamon()==castOther.getMamon()) || ( this.getMamon()!=null && castOther.getMamon()!=null && this.getMamon().equals(castOther.getMamon()) ) )
 && ( (this.getLop()==castOther.getLop()) || ( this.getLop()!=null && castOther.getLop()!=null && this.getLop().equals(castOther.getLop()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMamon() == null ? 0 : this.getMamon().hashCode() );
         result = 37 * result + ( getLop() == null ? 0 : this.getLop().hashCode() );
         return result;
   }   


}


