package pojos;
// Generated 04-Jun-2020 11:08:46 by Hibernate Tools 4.3.1

/**
 * Thoikhoabieu generated by hbm2java
 */
public class Thoikhoabieu implements java.io.Serializable {

    private String mamon;
    private String tenmon;
    private String phonghoc;
    private String lop;

    public Thoikhoabieu() {
    }

    public Thoikhoabieu(String mamon) {
        this.mamon = mamon;
    }

    public Thoikhoabieu(String mamon, String tenmon, String phonghoc, String lop) {
        this.mamon = mamon;
        this.tenmon = tenmon;
        this.phonghoc = phonghoc;
        this.lop = lop;
    }

    public String getMamon() {
        return this.mamon;
    }

    public void setMamon(String mamon) {
        this.mamon = mamon;
    }

    public String getTenmon() {
        return this.tenmon;
    }

    public void setTenmon(String tenmon) {
        this.tenmon = tenmon;
    }

    public String getPhonghoc() {
        return this.phonghoc;
    }

    public void setPhonghoc(String phonghoc) {
        this.phonghoc = phonghoc;
    }

    public void setLop(String lop) {
        this.lop = lop;
    }

    public String getLop() {
        return lop;
    }

}
