package pojos;
// Generated 20-Jun-2020 22:28:32 by Hibernate Tools 4.3.1



/**
 * ThoikhoabieuId generated by hbm2java
 */
public class ThoikhoabieuId  implements java.io.Serializable {


     private String mamon;
     private String lop;

    public ThoikhoabieuId() {
    }

    public ThoikhoabieuId(String mamon, String lop) {
       this.mamon = mamon;
       this.lop = lop;
    }
   
    public String getMamon() {
        return this.mamon;
    }
    
    public void setMamon(String mamon) {
        this.mamon = mamon;
    }
    public String getLop() {
        return this.lop;
    }
    
    public void setLop(String lop) {
        this.lop = lop;
    }




}


